[package]
name = "hello-from-cpp"
version = "0.1.0"
authors = ["ltg170 <ltg1710@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hello-sys = {path = "../crates/hello-sys"}
